% coil: coil structure generated by bemfmm_loadCoil
% origin: 1x3 vector: desired coil origin in model coordinate system
% axis: 1x3 vector: unit vector describing the new direction for a z-directed vector attached to the coil
% theta: scalar: angle in radians to rotate about the axis specified by input argument orientation

function coil = bemfmm_positionCoil(coil, origin, axis, theta)
    
    axis = axis/norm(axis); % Ensure unit length

    % Reset the coil to baseline
    coil.strcoil = coil.strcoil_base;
    coil.coilCAD = coil.coilCAD_base;
    
    % First transformation: rotate the coil about its axis
    coil.strcoil.Pwire = meshrotate2(coil.strcoil.Pwire, coil.centerlineDirection_base, theta);
    coil.coilCAD.P     = meshrotate2(coil.coilCAD.P, coil.centerlineDirection_base, theta);
    
    % Second transformation: Tilt the coil to point along its new axis
    coil.strcoil.Pwire = meshrotate1(coil.strcoil.Pwire, axis(1), axis(2), axis(3));
    coil.coilCAD.P     = meshrotate1(coil.coilCAD.P, axis(1), axis(2), axis(3));

    % Third transformation: Translate the coil to its new origin
    coil.strcoil.Pwire = coil.strcoil.Pwire + origin;
    coil.coilCAD.P     = coil.coilCAD.P + origin;
    
    % Update metadata
    coil.origin = origin;
    coil.centerlineDirection = axis;
    coil.centerlineTheta = theta;
    
end